all:
	
	g++ Triangulos.cpp -o Triangulos
	g++ LetraDni.cpp -o LetraDni
	g++ ComprobarDni.cpp -o ComprobarDni
	g++ CuadradosPerfectos.cpp -o CuadradosPerfectos
	g++ CuadradoPerfectoCercano.cpp -o CuadradosPerfectoCercano
	g++ DetectorRectangulo.cpp -o DetectorRectangulo
	g++ DetectorRectanguloMatroska.cpp -o DetectorRectanguloMatroska
	g++ MovimientosAjedrez.cpp -o MovimientosAjedrez
