all:
	g++ Ejercicio1.cpp -o Ejercicio1
	g++ Ejercicio2.cpp -o Ejercicio2
	g++ Ejercicio3.cpp -o Ejercicio3
	g++ Ejercicio4.cpp -o Ejercicio4
	g++ Ejercicio41.cpp -o Ejercicio41
	g++ Ejercicio4_revisado.cpp -o Ejercicio4revisado
	g++ Ejercicio5.cpp -o Ejercicio5
